// TypeScript Types for analyze-pitch-for-assets Edge Function
// Feature: Creative Asset Generation System
// Design: Isolated - accepts all data as parameters, NO database queries

// ============================================================================
// REQUEST TYPES (Input from frontend)
// ============================================================================

/**
 * Main request payload for analyzing pitch deck and generating asset ideas
 * ISOLATED DESIGN: All data passed as parameters, no DB lookups required
 */
export interface AnalyzePitchRequest {
  // Title identification (passed from UI, no DB lookup)
  title_id: string;           // External reference (UUID string or any ID)
  title_name: string;          // Displayed in UI, stored in results

  // Pitch deck content (passed from UI)
  pitch_deck_url: string;      // Supabase Storage URL (signed URL with 24h expiry)
  pitch_analysis?: PitchAnalysis; // Optional: Pre-extracted pitch analysis from title_content_analysis

  // Admin context (passed from auth)
  admin_email: string;         // Email of requesting admin (e.g., 'sungho@dadble.com')
}

/**
 * Pitch analysis structure from title_content_analysis.pitch_analysis JSONB field
 * Used to provide context for asset generation without querying database
 */
export interface PitchAnalysis {
  // Character information
  characters?: {
    main_characters?: Array<{
      name?: string;
      role?: string;
      archetype?: string;
      description?: string;
    }>;
    relationships?: string[];
  };

  // Story elements
  story?: {
    logline?: string;
    premise?: string;
    themes?: string[];
    conflicts?: string[];
    narrative_structure?: string;
    setting?: string;
  };

  // Market positioning
  market?: {
    target_audience?: string;
    comparable_titles?: string[];
    unique_selling_points?: string[];
    genre_blend?: string[];
  };

  // Source material metrics
  source_material?: {
    platform?: string;
    views?: number;
    chapters?: number;
    rating?: number;
    completion_status?: string;
  };

  // Cultural elements
  cultural_elements?: {
    korean_cultural_themes?: string[];
    cultural_authenticity_score?: number;
  };

  // Raw text (fallback if structured data incomplete)
  raw_pitch_text?: string;
}

// ============================================================================
// RESPONSE TYPES (Output to frontend)
// ============================================================================

/**
 * Success response with generated asset ideas
 */
export interface AnalyzePitchResponse {
  success: true;
  data: {
    title_id: string;
    title_name: string;
    assets_created: number;         // Count of asset ideas inserted
    asset_ideas: AssetIdea[];       // Array of generated asset ideas
    analysis_metadata: AnalysisMetadata;
  };
}

/**
 * Error response
 */
export interface AnalyzePitchError {
  success: false;
  error: {
    code: string;                   // Error code (e.g., 'PITCH_MISSING', 'OPENAI_ERROR')
    message: string;                // Human-readable error message
    details?: unknown;              // Optional error details
  };
}

/**
 * Union type for response
 */
export type AnalyzePitchResult = AnalyzePitchResponse | AnalyzePitchError;

// ============================================================================
// ASSET IDEA TYPES
// ============================================================================

/**
 * Asset category classification
 */
export type AssetCategory = 'social_media' | 'ad_creative' | 'pitch_material';

/**
 * Asset types by category
 */
export type SocialMediaAssetType =
  | 'instagram_story'
  | 'instagram_post'
  | 'facebook_post'
  | 'twitter_post'
  | 'tiktok_video';

export type AdCreativeAssetType =
  | 'display_ad'
  | 'youtube_thumbnail'
  | 'video_ad'
  | 'banner_ad';

export type PitchMaterialAssetType =
  | 'concept_art'
  | 'key_scene'
  | 'character_card'
  | 'mood_board'
  | 'poster';

export type AssetType = SocialMediaAssetType | AdCreativeAssetType | PitchMaterialAssetType;

/**
 * Asset format (dimensions or video specs)
 */
export type AssetFormat =
  | '1080x1920'    // Instagram Story, TikTok
  | '1080x1080'    // Instagram Square Post
  | '1200x628'     // Facebook Link Post
  | '1200x675'     // Twitter Large Card
  | '1280x720'     // YouTube Thumbnail
  | '300x250'      // Display Ad (Medium Rectangle)
  | '728x90'       // Display Ad (Leaderboard)
  | '1920x1080'    // Video Ad, Concept Art, Poster
  | 'custom';      // Custom dimensions

/**
 * Generation API options
 */
export type GenerationAPI = 'dall-e-3' | 'openai-video';

/**
 * Generation model options
 */
export type GenerationModel = 'dall-e-3' | 'dall-e-3-hd';

/**
 * Asset idea generated by GPT-4
 * Maps directly to title_marketing_assets table structure
 */
export interface AssetIdea {
  // Categorization
  asset_category: AssetCategory;
  asset_type: AssetType;
  asset_format: AssetFormat;

  // Content
  description: string;             // What this asset represents (user-facing)
  prompt_template: string;         // DALL-E 3 prompt generated by GPT-4

  // Generation config
  generation_api: GenerationAPI;
  generation_model: GenerationModel;

  // Metadata (optional, for display/filtering)
  priority?: number;               // 1-5, higher = more important
  estimated_cost?: number;         // Estimated cost in USD
}

// ============================================================================
// ANALYSIS METADATA
// ============================================================================

/**
 * Metadata about the analysis process
 */
export interface AnalysisMetadata {
  // Cost tracking
  gpt4_cost: number;               // Cost of GPT-4 analysis in USD
  total_cost: number;              // Total cost (currently just GPT-4)

  // Timing
  analysis_duration_ms: number;    // Time taken for analysis

  // OpenAI metadata
  model_used: string;              // e.g., 'gpt-4-turbo-preview'
  tokens_used: {
    prompt: number;
    completion: number;
    total: number;
  };

  // Content metadata
  pitch_analysis_used: boolean;    // Whether pitch_analysis was available
  ideas_generated: number;         // Count of ideas generated by GPT-4
}

// ============================================================================
// GPT-4 RESPONSE TYPES
// ============================================================================

/**
 * Expected structure of GPT-4 response
 * GPT-4 will be prompted to return JSON in this format
 */
export interface GPT4AssetAnalysisResponse {
  asset_ideas: Array<{
    category: AssetCategory;
    type: string;                  // Will be mapped to AssetType
    format: AssetFormat;
    description: string;
    prompt: string;                // DALL-E 3 prompt
    priority?: number;
    notes?: string;                // Optional reasoning
  }>;
  summary?: string;                // Optional: Overall strategy summary
}

// ============================================================================
// DATABASE INSERT TYPES
// ============================================================================

/**
 * Row to insert into title_marketing_assets table
 * Uses isolated design (no foreign keys)
 */
export interface MarketingAssetInsert {
  // Title reference (TEXT, not FK)
  title_id: string;
  title_name: string;

  // Asset details
  asset_category: AssetCategory;
  asset_type: string;              // Maps to asset_type TEXT field
  asset_format: string;

  // Content
  description: string;
  prompt_template: string;
  prompt_used: null;               // Will be set when admin edits prompt

  // URLs (null initially, set during generation)
  image_url: null;
  video_url: null;

  // Generation metadata
  generation_api: GenerationAPI;
  generation_model: GenerationModel;
  generation_cost: 0;              // Updated when generated
  generation_attempts: 0;          // Incremented on each attempt
  error_message: null;

  // Status
  status: 'pending';               // Always 'pending' when created by this function

  // Approval (null initially)
  approved: false;
  approved_by_email: null;
  approved_at: null;
}

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Configuration for asset generation
 */
export interface AssetGenerationConfig {
  // Number of ideas to generate per category
  social_media_count: number;      // Default: 5
  ad_creative_count: number;       // Default: 5
  pitch_material_count: number;    // Default: 5

  // Model configuration
  gpt4_model: string;              // Default: 'gpt-4-turbo-preview'
  temperature: number;             // Default: 0.7 (creative but controlled)

  // Cost limits
  max_cost_usd: number;            // Default: 0.10 (safety limit)
}

/**
 * Default configuration
 */
export const DEFAULT_CONFIG: AssetGenerationConfig = {
  social_media_count: 5,
  ad_creative_count: 5,
  pitch_material_count: 5,
  gpt4_model: 'gpt-4-turbo-preview',
  temperature: 0.7,
  max_cost_usd: 0.10,
};

// ============================================================================
// VALIDATION HELPERS
// ============================================================================

/**
 * Type guard: Check if response is success
 */
export function isSuccessResponse(
  result: AnalyzePitchResult
): result is AnalyzePitchResponse {
  return result.success === true;
}

/**
 * Type guard: Check if response is error
 */
export function isErrorResponse(
  result: AnalyzePitchResult
): result is AnalyzePitchError {
  return result.success === false;
}

/**
 * Validate asset category
 */
export function isValidAssetCategory(category: string): category is AssetCategory {
  return ['social_media', 'ad_creative', 'pitch_material'].includes(category);
}

/**
 * Validate asset format
 */
export function isValidAssetFormat(format: string): format is AssetFormat {
  const validFormats: AssetFormat[] = [
    '1080x1920',
    '1080x1080',
    '1200x628',
    '1200x675',
    '1280x720',
    '300x250',
    '728x90',
    '1920x1080',
    'custom',
  ];
  return validFormats.includes(format as AssetFormat);
}

// ============================================================================
// COST CALCULATION HELPERS
// ============================================================================

/**
 * GPT-4 Turbo pricing (as of 2025-11-06)
 */
export const GPT4_PRICING = {
  'gpt-4-turbo-preview': {
    input: 0.01 / 1000,    // $0.01 per 1K tokens
    output: 0.03 / 1000,   // $0.03 per 1K tokens
  },
  'gpt-4': {
    input: 0.03 / 1000,    // $0.03 per 1K tokens
    output: 0.06 / 1000,   // $0.06 per 1K tokens
  },
};

/**
 * Calculate GPT-4 cost based on token usage
 */
export function calculateGPT4Cost(
  model: string,
  promptTokens: number,
  completionTokens: number
): number {
  const pricing = GPT4_PRICING[model as keyof typeof GPT4_PRICING] || GPT4_PRICING['gpt-4-turbo-preview'];
  return (promptTokens * pricing.input) + (completionTokens * pricing.output);
}

/**
 * DALL-E 3 pricing (as of 2025-11-06)
 */
export const DALLE3_PRICING = {
  'dall-e-3': 0.040,       // Standard quality: $0.040 per image
  'dall-e-3-hd': 0.080,    // HD quality: $0.080 per image
};

/**
 * Calculate estimated cost for asset generation
 */
export function estimateAssetCost(
  generation_api: GenerationAPI,
  generation_model: GenerationModel
): number {
  if (generation_api === 'dall-e-3') {
    return DALLE3_PRICING[generation_model] || DALLE3_PRICING['dall-e-3'];
  }
  // Future: openai-video pricing
  return 0;
}
